Repository projectsyn/component-topolvm, pull requests merged in 2021-11, with the labels that each got.

#14 Use Kapitan Helm dependency type to fetch TopoLVM Helm chart
  class/defaults.yml
  class/topolvm.yml
Labels: change

#15 Update helmchart to 3.1.2
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: dependency

#16 Fix certificate duration definition
  class/topolvm.yml
  postprocess/patch_certificates.jsonnet
Labels: bug

#17 Disable scheduler PDB when scheduler is disabled
  class/defaults.yml
Labels: bug

#18 Fix issue that cert-manager might accidentally be deployed
  class/topolvm.yml
Labels: bug
